
version: '3'

services:
  
  postgres:
    image: postgres:latest
    container_name: database
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data:Z
    
  pgadmin:
    container_name: pgadminemotion
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80"

volumes:
  db_data: